# The URL the site will be built for
base_url = "https://www.munich-embedded.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

default_language = "de"

[languages]
[languages.en]
title = "Munich Embedded"

[languages.en.translations]
linkedin_tooltip = "Follow our LinkedIn Page"
github_tooltip = "Munich Embedded GitHub Organization"
youtube_tooltip = "Visit our YouTube Channel"
newsletter = "Newsletter"
newsletter_tooltip = "Subscribe to our Newsletter"
imprint = "Imprint"
privacy_policy = "Privacy Policy"
all_rights_reserved = "All rights reserved"

[translations]
linkedin_tooltip = "Unserer LinkedIn Seite folgen"
github_tooltip = "Munich Embedded GitHub Organization"
youtube_tooltip = "Unseren YouTube Kanal besuchen"
newsletter = "Newsletter"
newsletter_tooltip = "Unseren Newsletter abonnieren"
imprint = "Impressum"
privacy_policy = "Datenschutz"
all_rights_reserved = "Alle Rechte vorbehalten"

[markdown.highlighting]
light_theme = "github-light-default"
dark_theme = "github-dark-default"

[extra]
# Put all your custom variables here
